available-pronouns:
  - he
  - she
  - they
  - it
  - any
  - other
  - ask
  - username
  - ze
  - xe
  - ey
  - ve
  - ne

handle-chat: true

message-prefix: "PronounMC: "

verbose-logging: false
log-changes: true

enable-third-party-override: true
third-party-override: "pronoundb"