name: PronounMC
version: '${project.version}'
main: dev.mxace.pronounmc.PronounMC
api-version: 1.13

commands:
  pronounmc:
    description: "Opens a GUI which lets you change your pronouns."
    usage: "/pronounmc"

  viewpronouns:
    description: "Lists a player's pronouns to the sender."
    usage: "/viewpronouns [player]" # If no player is specified, default to the sender.