name: PronounMC
version: '2025.1'
main: dev.mxace.pronounmc.PronounMC
api-version: '1.21'
authors: [ _Mx_Ace ]
description: Allows for complex manipulation of incoming chat messages.
softdepend: [ PlaceholderAPI ]
commands:
  setpronouns:
    description: Modify your preferred pronouns.
    usage: /setpronouns <pronouns> [player]
  clearpronouns:
    description: Removes your preferred pronouns from the database.
    usage: /clearpronouns [player]
  pronounsnote:
    description: Presents a possible note attached to a set of pronouns to the player.
    usage: /pronounsnote <pronouns>
  reloadpronounmc:
    description: Reloads the PronounMC plugin.
    usage: /reloadpronounmc