name: PronounMC
description: See someone's pronouns
version: 0.5
author: AceKiron

main: io.github.acekiron.pronounmc.PMCPlugin
api-version: 1.18

commands:
   addpronouns:
      description: Add pronouns
   removepronouns:
      description: Remove pronouns
   getpronouns:
      description: Get pronouns

permissions:
   pronounmc.modify:
      description: Set your own pronouns
   pronounmc.modify.other:
      description: Set someone else's pronouns
   pronounmc.get:
      description: Get pronouns