name: PronounMC
main: io.github.acekiron.pronounmc.PMCPlugin
version: 0.3
api-version: 1.18
description: See someone's pronouns
commands:
  setpronouns:
    description: Set your own pronouns
  getpronouns:
    description: See someone's pronouns
permissions:
  pronounmc.set:
    description: Set pronouns
  pronounmc.get:
    description: Get pronouns