name: Build and test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - run: mvn package