name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - rewrite
    paths:
      - "**.java"
      - "**.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.5
      
      - name: Compile PronounMC
        run: mvn clean package
    
      - name: Upload PronounMC JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pronounmc-jar
          path: ./target/pronounmc-*.jar