name: Build
on:
  push:
    branches:
      - main
      - integration_pronoundb
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.3
        
      - run: mvn clean package
