name: Build
on:
  push:
    branches:
      - 1.17.1
      - 1.18.1
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Build PronounMC
      uses: SpraxDev/Action-SpigotMC@v3
      with:
        versions: 1.18.1
