name: Build and upload artifact
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 21
          
      - run: mvn package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pmc-base
          path: target/PronounMC-*.jar