name: Build and test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        
      - run: mvn package

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pronounmc-jar
          path: ./target/pronounmc-*.jar