name: Licensed

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v3
      
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      
      - uses: github/setup-licensed@v1
        with:
          version: '4.4.0`

      - run: licensed list
