name: Licensed

on:
  push:
    branches:
      - 1.17.1
      - 1.18.1
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup github/licensed
        uses: jonabc/setup-licensed@v1.1.1
        with:
          version: 3.x
      
      - run: licensed status
